/**
 * Generated by `cua codegen` from member.lookup_savings_balance@1.2.0 (Look up a member's savings balance).
 * Standalone Playwright automation: primary locator strategies with fallbacks, recorded
 * pre/post-conditions and the checkpoint. Run: npx tsx <this file>
 * Inputs: {"member_id":"10024"}  Tenant: summit
 */
import { chromium, type Frame, type Locator, type Page } from "playwright";

const inputs: Record<string, string> = {
  "member_id": "10024"
};
const outputs: Record<string, unknown> = {};

async function first(frame: Frame | null, candidates: Array<(f: Frame) => Locator>, what: string): Promise<Locator> {
  if (!frame) throw new Error(`frame not found for ${what}`);
  const deadline = Date.now() + 10000;
  while (Date.now() < deadline) {
    for (const c of candidates) {
      const loc = c(frame);
      const n = await loc.count().catch(() => 0);
      if (n === 1 && (await loc.first().isVisible().catch(() => false))) return loc.first();
    }
    await new Promise((r) => setTimeout(r, 200));
  }
  throw new Error(`could not resolve ${what}`);
}
async function waitFor(cond: () => Promise<boolean> | boolean, what: string, ms = 10000): Promise<void> {
  const deadline = Date.now() + ms;
  while (Date.now() < deadline) {
    if (await cond()) return;
    await new Promise((r) => setTimeout(r, 200));
  }
  throw new Error(`expectation failed: ${what}`);
}
async function settle(page: Page): Promise<void> {
  await page.waitForLoadState("load").catch(() => {});
  await page.waitForTimeout(300);
}
function parse(kind: string, raw: string): unknown {
  const t = raw.trim();
  if (kind === "currency") return Number(t.replace(/[^0-9.-]/g, "")) * (/^\(.*\)$/.test(t) ? -1 : 1);
  if (kind === "number") return Number(t.replace(/,/g, ""));
  return t;
}

async function main(): Promise<void> {
  const browser = await chromium.launch({ headless: process.env.HEADED !== "1" });
  const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
  try {
    // --- session bootstrap (from app profile legacycore-teller; the password comes from the environment)
    await page.goto("http://localhost:4173/t/summit/");
    await settle(page);
  // Enter the teller user id
  await (await first(page.frame("main"), [
      (f) => f.locator("xpath=//td[normalize-space()='User ID']/following-sibling::td[1]//*[self::input or self::select or self::textarea]"),
      (f) => f.locator("form input[type=\"text\"]"),
    ], "the \"User ID\" text box in frame main")).fill("teller1");
  await settle(page);
  // Enter the teller password
  await (await first(page.frame("main"), [
      (f) => f.locator("xpath=//td[normalize-space()='Password']/following-sibling::td[1]//*[self::input or self::select or self::textarea]"),
      (f) => f.locator("input[type=\"password\"]"),
    ], "the \"Password\" box in frame main")).fill((process.env["LEGACYCORE_PASSWORD"] ?? ""));
  await settle(page);
  // Submit the sign-on form
  await (await first(page.frame("main"), [
      (f) => f.locator("input[type=\"submit\"]"),
      (f) => f.getByRole("button", { name: "Sign On", exact: true }),
    ], "the sign-on button in frame main")).click();
  await settle(page);
  // any-of expectation (3 alternatives) — checked at replay, simplified here

    // --- capability steps
  // Click the link "Member Inquiry" in frame nav — Open the member inquiry function from the menu
  await waitFor(() => /^http:\/\/localhost:4173\/t\/summit\/home(\?.*)?$/.test(page.frame("main").url()), "url matches ^{{base_url}}/home(\\?.*)?$");
  await waitFor(async () => (await page.frame("main").evaluate(() => document.body?.innerText ?? "")).includes("Welcome, teller1") === true, "text \"Welcome, {{teller_user}}\" present");
  await (await first(page.frame("nav"), [
      (f) => f.getByRole("link", { name: "Member Inquiry", exact: true }),
      (f) => f.locator("a", { hasText: "Member Inquiry" }),
      (f) => f.locator("a[href=\"/t/summit/inquiry\"]"),
      (f) => f.locator("body > table > tbody > tr:nth-of-type(2) > td > font > a"),
      (f) => f.locator("xpath=/html[1]/body[1]/table[1]/tbody[1]/tr[2]/td[1]/font[1]/a[1]"),
    ], "the link \"Member Inquiry\" in frame nav")).click();
  await settle(page);
  await waitFor(() => /^http:\/\/localhost:4173\/t\/summit\/inquiry(\?.*)?$/.test(page.frame("main").url()), "url matches ^{{base_url}}/inquiry(\\?.*)?$");
  await waitFor(async () => (await page.frame("main").evaluate(() => document.body?.innerText ?? "")).includes("Member Inquiry") === true, "text \"Member Inquiry\" present");

  // Enter {{member_id}} into the textbox "Member Number" in frame main — Enter the member number to search for
  await waitFor(() => /^http:\/\/localhost:4173\/t\/summit\/inquiry(\?.*)?$/.test(page.frame("main").url()), "url matches ^{{base_url}}/inquiry(\\?.*)?$");
  await waitFor(async () => (await page.frame("main").evaluate(() => document.body?.innerText ?? "")).includes("Member Inquiry") === true, "text \"Member Inquiry\" present");
  await (await first(page.frame("main"), [
      (f) => f.locator("xpath=//td[normalize-space()='Member Number']/following-sibling::td[1]//*[self::input or self::select or self::textarea]"),
      (f) => f.locator("input[name=\"memberno\"][type=\"text\"]"),
      (f) => f.locator("body > form > table > tbody > tr:nth-of-type(1) > td:nth-of-type(2) > input"),
      (f) => f.locator("xpath=/html[1]/body[1]/form[1]/table[1]/tbody[1]/tr[1]/td[2]/input[1]"),
    ], "the textbox \"Member Number\" in frame main")).fill(inputs["member_id"]);
  await settle(page);

  // Click the button "Search" in frame main — Run the search
  await waitFor(() => /^http:\/\/localhost:4173\/t\/summit\/inquiry(\?.*)?$/.test(page.frame("main").url()), "url matches ^{{base_url}}/inquiry(\\?.*)?$");
  await waitFor(async () => (await page.frame("main").evaluate(() => document.body?.innerText ?? "")).includes("Member Inquiry") === true, "text \"Member Inquiry\" present");
  await (await first(page.frame("main"), [
      (f) => f.getByRole("button", { name: "Search", exact: true }),
      (f) => f.locator("input", { hasText: "Search" }),
      (f) => f.locator("input[type=\"button\"][value=\"Search\"]"),
      (f) => f.locator("body > form > table > tbody > tr:nth-of-type(3) > td:nth-of-type(2) > input"),
      (f) => f.locator("xpath=/html[1]/body[1]/form[1]/table[1]/tbody[1]/tr[3]/td[2]/input[1]"),
    ], "the button \"Search\" in frame main")).click();
  await settle(page);
  await waitFor(async () => (await page.frame("main").evaluate(() => document.body?.innerText ?? "")).includes("Search Results") === true, "text \"Search Results\" present");

  // Click the link "{{member_id}}" in frame main — Open the matching member's profile
  await waitFor(() => /^http:\/\/localhost:4173\/t\/summit\/inquiry(\?.*)?$/.test(page.frame("main").url()), "url matches ^{{base_url}}/inquiry(\\?.*)?$");
  await waitFor(async () => (await page.frame("main").evaluate(() => document.body?.innerText ?? "")).includes("Search Results") === true, "text \"Search Results\" present");
  await (await first(page.frame("main"), [
      (f) => f.getByRole("link", { name: "10024", exact: true }),
      (f) => f.locator("a", { hasText: "10024" }),
      (f) => f.locator("xpath=//table//tr[td[count(../../tr[1]/*[normalize-space()='Member #']/preceding-sibling::*)+1][normalize-space()='10024']]/td[count(../../tr[1]/*[normalize-space()='Member #']/preceding-sibling::*)+1]//a"),
      (f) => f.locator("a[href=\"javascript:goMember('10024')\"]"),
      (f) => f.locator("body > table:nth-of-type(2) > tbody > tr:nth-of-type(2) > td:nth-of-type(1) > a"),
      (f) => f.locator("xpath=/html[1]/body[1]/table[2]/tbody[1]/tr[2]/td[1]/a[1]"),
    ], "the link \"{{member_id}}\" in frame main")).click();
  await settle(page);
  await waitFor(() => /^http:\/\/localhost:4173\/t\/summit\/member\/10024(\?.*)?$/.test(page.frame("main").url()), "url matches ^{{base_url}}/member/{{member_id}}(\\?.*)?$");
  await waitFor(async () => (await page.frame("main").evaluate(() => document.body?.innerText ?? "")).includes("Member Profile") === true, "text \"Member Profile\" present");

  // Read savings_balance from the "Balance" cell of the row where Type = "Savings" in frame main — Read the current balance of the Savings share
  await waitFor(() => /^http:\/\/localhost:4173\/t\/summit\/member\/10024(\?.*)?$/.test(page.frame("main").url()), "url matches ^{{base_url}}/member/{{member_id}}(\\?.*)?$");
  await waitFor(async () => (await page.frame("main").evaluate(() => document.body?.innerText ?? "")).includes("Member Profile") === true, "text \"Member Profile\" present");
  outputs["savings_balance"] = parse("currency", await (await first(page.frame("main"), [
      (f) => f.locator("xpath=//table//tr[td[count(../../tr[1]/*[normalize-space()='Type']/preceding-sibling::*)+1][normalize-space()='Savings']]/td[count(../../tr[1]/*[normalize-space()='Balance']/preceding-sibling::*)+1]"),
      (f) => f.locator("body > table:nth-of-type(4) > tbody > tr:nth-of-type(2) > td:nth-of-type(4)"),
      (f) => f.locator("xpath=/html[1]/body[1]/table[4]/tbody[1]/tr[2]/td[4]"),
    ], "the \"Balance\" cell of the row where Type = \"Savings\" in frame main")).innerText());
  await settle(page);

    // --- checkpoint: The member profile with the Accounts table is displayed for the requested member.
  await waitFor(() => /^http:\/\/localhost:4173\/t\/summit\/member\/10024(\?.*)?$/.test(page.frame("main").url()), "url matches ^{{base_url}}/member/{{member_id}}(\\?.*)?$");
  await waitFor(async () => (await page.frame("main").evaluate(() => document.body?.innerText ?? "")).includes("Accounts") === true, "text \"Accounts\" present");
    console.log(JSON.stringify({ status: "success", outputs }, null, 2));
  } catch (e) {
    console.log(JSON.stringify({ status: "failure", error: e instanceof Error ? e.message : String(e) }, null, 2));
    process.exitCode = 1;
  } finally {
    await browser.close();
  }
}

main();
